name: .NET CI

on:
  push:                # Tự chạy khi có push
  pull_request:        # Tự chạy khi có PR
  workflow_dispatch:   # 👈 Thêm dòng này để bật nút "Run workflow"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --no-restore -c Release

      - name: Test (NUnit)
        run: dotnet test --no-build -c Release --verbosity normal
